### ISSUE TITLE
block zoom / max zoom issue

### ISSUE THREAD

**Issue by Cammagno** [javalent/obsidian-leaflet#272]
I wanted to have an image map that doesn't zoom at all.
So, I've tried to put the MinZoom and MaxZoom equal to DefaultZoom, let's say all to 8.
With MinZoom no problem, my map doesn't zoom out anymore.
But with MaxZoom I had a problem: the map zoomed in (it does not zoom in anymore, but it's not visualized at the default zoom level, but a greater one).
So I tried to bring back MinZoom to 1 and it does not change anything.
When DefaultZoom and MaxZoom are the same, the map is always visualized all zoomed in, no matter which the level is

![Min8-Def8-Max10](https://user-images.githubusercontent.com/95725064/150673895-617f6f1c-a42b-48f9-bf99-4aa7bbd00d7f.PNG)
![Min8-Def8-Max8](https://user-images.githubusercontent.com/95725064/150673883-e367da14-d685-4f79-a228-0e4f01e69888.PNG)

.

**Comment by Servinjesus1** [comment]
This addresses a similar, more general, issue I have with image maps in that the zoom bounds can't be reasonably set for any image map. Why does modifying `minZoom` relative to `maxZoom` change the absolute minimum zoom of the image such that viewing the image at `maxZoom` always looks the same? This imposes a hard limit on the maximum zoom of any image (even `svg`s)

This doesn't allow for full zoom control. Is that possible? Ideally a zoom of 1 might mean 1 pixel = 1 screen-space pixel (or maybe, fit image to leaflet size?). This works for `svg`s too, as they have an intrinsic "nominal pixel size" attribute. Then, `Zoom` would be relative to the pixel presentation size and fully controllable. It may be dependent on leaflet size (for the latter idea of what `Zoom = 1` means), but maybe that's better since it allows for consistent "field of view" for the image (smaller leaflets have less real estate, meaning its max zoom should be less, to avoid getting lost)

OP's request for static size would then be possible, _and_ that static size adjustable. Right now, you can only shrink the image or see it at full zoom. Neither has been ideal for any of the image maps I've tried to make.

**Comment by valentine195** [comment]
Try setting your [bounds](https://github.com/valentine195/obsidian-leaflet-plugin#bounds). This should fix your zoom related issues. 

unfortunately the way image overlays work in Leaflet doesn’t play super well with things like this, as far as I know

**Comment by Servinjesus1** [comment]
@valentine195 Thanks, enforcing [bounds](https://github.com/valentine195/obsidian-leaflet-plugin#bounds) worked, however that's a really confusing part of the manual. It seems that, and [the proceeding section](https://github.com/valentine195/obsidian-leaflet-plugin#latitude-and-longtitude-of-image-maps) should be flipped, and the readme changed to reflect that it's not `top-left-latitude` etc, but `top-left-%-from-top-left`...

For @Cammagno (to close the issue):
1. Set bounds to:
   ```yaml
   bounds:
      - [ 0, 0 ]
      - [ 100, 100 ]
   ```
1. Set `minZoom`, `maxZoom`, and `defaultZoom` to the desired locked `zoom`
   > Some combination of two of the three would likely lock the image, too, but I see that as a haphazard product of undefined state rather than a true solution...
1. Profit.

**Comment by Cammagno** [comment]
> * Set bounds to:
>   ```yaml
>   bounds:
>      - [ 0, 0 ]
>      - [ 100, 100 ]
>   ```

Unfortunately, I never managed to have bounds work properly :(
If I set bounds as you suggested, my images deforms to square ones.

**Comment by valentine195** [comment]
You have to set your bounds specific to your image's ratio. The image will fit exactly inside the bounds you specify, so if you specify a square, your image will become a square.

For example, a 1920x1080 image will be something like `[0,0],[56,100]`

**Comment by valentine195** [comment]
However, I agree that the docs are unclear. I will work to improve them as I have time. If anyone wants to help, please feel free 😃

**Comment by Cammagno** [comment]
> You have to set your bounds specific to your image's ratio. The image will fit exactly inside the bounds you specify, so if you specify a square, your image will become a square.
> 
> For example, a 1920x1080 image will be something like `[0,0],[56,100]`

Thank for your replay.
I was under the impression that the number in brackets were percentile, so I thought that [100, 100] was meaning 100% of the original height and 100% of the original width.
So, instead,: 
- do I have to always use 100 for the width and the proper number (calculated based on the image's ratio) for the height
OR
 - do I have to always use 100 for the greater dimension and the proper number (calculated based on the image's ratio) for the other one?
 In other terms, according to your example, if my image is instead a portrait one 1080x1920, should I use `[0,0],[100,56]' or `[0,0],[177,100]'?
 
 TIA!

**Comment by valentine195** [comment]
The bounds can be whatever you want, actually. 

It's pretty common to find some measurement system on the image, measure it in pixels to get a pixel per mile (or whatever unit), and then convert the image size to miles. 

There is a [discussion](https://github.com/valentine195/obsidian-leaflet-plugin/discussions/130) talking about this, and a community member made a [video walkthrough](https://www.youtube.com/watch?v=54EyMzJP5DU).

**Comment by Cammagno** [comment]
> There is a [discussion](https://github.com/valentine195/obsidian-leaflet-plugin/discussions/130) talking about this

Thanks, now I've got how it works :)
